# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/kryan/IdeaProjects/Cprogramming/CprogrammingIntro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/kryan/IdeaProjects/Cprogramming/CprogrammingIntro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/kryan/IdeaProjects/Cprogramming/CprogrammingIntro/CMakeFiles /mnt/c/Users/kryan/IdeaProjects/Cprogramming/CprogrammingIntro/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/kryan/IdeaProjects/Cprogramming/CprogrammingIntro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Cprogramming

# Build rule for target.
Cprogramming: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Cprogramming
.PHONY : Cprogramming

# fast build rule for target.
Cprogramming/fast:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/build
.PHONY : Cprogramming/fast

2darray.o: 2darray.c.o

.PHONY : 2darray.o

# target to build an object file
2darray.c.o:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/2darray.c.o
.PHONY : 2darray.c.o

2darray.i: 2darray.c.i

.PHONY : 2darray.i

# target to preprocess a source file
2darray.c.i:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/2darray.c.i
.PHONY : 2darray.c.i

2darray.s: 2darray.c.s

.PHONY : 2darray.s

# target to generate assembly for a file
2darray.c.s:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/2darray.c.s
.PHONY : 2darray.c.s

array.o: array.c.o

.PHONY : array.o

# target to build an object file
array.c.o:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/array.c.o
.PHONY : array.c.o

array.i: array.c.i

.PHONY : array.i

# target to preprocess a source file
array.c.i:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/array.c.i
.PHONY : array.c.i

array.s: array.c.s

.PHONY : array.s

# target to generate assembly for a file
array.c.s:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/array.c.s
.PHONY : array.c.s

linkedlist.o: linkedlist.c.o

.PHONY : linkedlist.o

# target to build an object file
linkedlist.c.o:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/linkedlist.c.o
.PHONY : linkedlist.c.o

linkedlist.i: linkedlist.c.i

.PHONY : linkedlist.i

# target to preprocess a source file
linkedlist.c.i:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/linkedlist.c.i
.PHONY : linkedlist.c.i

linkedlist.s: linkedlist.c.s

.PHONY : linkedlist.s

# target to generate assembly for a file
linkedlist.c.s:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/linkedlist.c.s
.PHONY : linkedlist.c.s

readfile.o: readfile.c.o

.PHONY : readfile.o

# target to build an object file
readfile.c.o:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/readfile.c.o
.PHONY : readfile.c.o

readfile.i: readfile.c.i

.PHONY : readfile.i

# target to preprocess a source file
readfile.c.i:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/readfile.c.i
.PHONY : readfile.c.i

readfile.s: readfile.c.s

.PHONY : readfile.s

# target to generate assembly for a file
readfile.c.s:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/readfile.c.s
.PHONY : readfile.c.s

string_calls.o: string_calls.c.o

.PHONY : string_calls.o

# target to build an object file
string_calls.c.o:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/string_calls.c.o
.PHONY : string_calls.c.o

string_calls.i: string_calls.c.i

.PHONY : string_calls.i

# target to preprocess a source file
string_calls.c.i:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/string_calls.c.i
.PHONY : string_calls.c.i

string_calls.s: string_calls.c.s

.PHONY : string_calls.s

# target to generate assembly for a file
string_calls.c.s:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/string_calls.c.s
.PHONY : string_calls.c.s

test.o: test.c.o

.PHONY : test.o

# target to build an object file
test.c.o:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i

.PHONY : test.i

# target to preprocess a source file
test.c.i:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s

.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	$(MAKE) -f CMakeFiles/Cprogramming.dir/build.make CMakeFiles/Cprogramming.dir/test.c.s
.PHONY : test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Cprogramming"
	@echo "... 2darray.o"
	@echo "... 2darray.i"
	@echo "... 2darray.s"
	@echo "... array.o"
	@echo "... array.i"
	@echo "... array.s"
	@echo "... linkedlist.o"
	@echo "... linkedlist.i"
	@echo "... linkedlist.s"
	@echo "... readfile.o"
	@echo "... readfile.i"
	@echo "... readfile.s"
	@echo "... string_calls.o"
	@echo "... string_calls.i"
	@echo "... string_calls.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

